### ISSUE TITLE
Cannot read property 'stop' of undefined at Object.stop 

### ISSUE THREAD

**Issue by netwrkx** [rishantagarwal/CordovaBackgroundGeolocationStartingUpExample#1]
ionic.bundle.js:25642 TypeError: Cannot read property 'stop' of undefined at Object.stop (services.js:81) at Scope.$scope.stopGeolocation (controllers.js:11) at fn (eval at <anonymous> (ionic.bundle.js:1), <anonymous>:4:236) at ionic.bundle.js:62386 at Scope.$eval (ionic.bundle.js:29158) at Scope.$apply (ionic.bundle.js:29257) at HTMLButtonElement.<anonymous> (ionic.bundle.js:62385) at HTMLButtonElement.eventHandler (ionic.bundle.js:16583) at triggerMouseEvent (ionic.bundle.js:2948) at tapClick (ionic.bundle.js:2937)

**Comment by rishantagarwal** [comment]
@netwrkx  Did you install the plugin first ? Its saying "bgGeo" to be undefined which can happen only if the plugin is not loaded . I tried running the project again , and it has no issues . Please get back to me if the issue continues.

**Comment by rishantagarwal** [comment]
`$ cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation-lt.git`
