### ISSUE TITLE
 Cannot read property 'configure' of undefined at Object.initialize

### ISSUE THREAD

**Issue by netwrkx** [rishantagarwal/CordovaBackgroundGeolocationStartingUpExample#2]
ionic.bundle.js:25642 TypeError: Cannot read property 'configure' of undefined at Object.initialize (services.js:29) at Scope.$scope.startGeolocation (controllers.js:6) at fn (eval at <anonymous> (ionic.bundle.js:26457), <anonymous>:4:239) at ionic.bundle.js:62386 at Scope.$eval (ionic.bundle.js:29158) at Scope.$apply (ionic.bundle.js:29257) at HTMLButtonElement.<anonymous> (ionic.bundle.js:62385) at HTMLButtonElement.eventHandler (ionic.bundle.js:16583) at triggerMouseEvent (ionic.bundle.js:2948) at tapClick (ionic.bundle.js:2937)

**Comment by rishantagarwal** [comment]
It has to be the same issue as [Issue #1 ](https://github.com/rishantagarwal/CordovaBackgroundGeolocationStartingUpExample/issues/1).

Please try installing the plugin.

**Comment by rishantagarwal** [comment]
`$ cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation-lt.git`

**Comment by netwrkx** [comment]
problem persist, same issue as [Issue #1](https://github.com/rishantagarwal/CordovaBackgroundGeolocationStartingUpExample/issues/1) .
installed `com.transistorsoft.cordova.background-geolocation`
installed `cordova-plugin-dialogs`

**Comment by rishantagarwal** [comment]
I am unable to recreate the error. If you have installed the plugins and this issue is still there , then only thing which might be happening is that Ionic has not yet finished loading the plugins , until you are trying to access it. So, it throws an error here. 

`.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {`

Also, this thing should handle the above error , but it doesn't. 

Maybe paste your code here , and I will look into it .

**Comment by rishantagarwal** [comment]
I cross checked by running app on  a completely new installation of Mac OS.  No issues found .

Steps I used :-
1. Git cloned the repo.
2. Installed npm through Node
3. Used `npm install` to install required packages.
4. Installed cordova through `npm install -g cordova`
5. Then added cordova plugin through `cordova plugin add https://github.com/transistorsoft/cordova-background-geolocation-lt.git`
6. Then added ios as platform `cordova platform add ios`
7. Then build the project using `cordova build`
8. App is ready !
